name: Build Module5_Sample_HW

on:
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build_Module5_Sample_HW.yml'
    - 'azure-de10nano-document/sensor-aggregation-reference-design-for-azure/hw/**'
  workflow_dispatch:

jobs:
  build-tutorials-job:
    name: Build ${{matrix.example}} with Quartus-${{matrix.qver}}
    strategy:
      matrix:
        qver: [17_595, 20_720]
        example: ['Module5_Sample_HW']
      fail-fast: false
    runs-on: ubuntu-18.04

    steps:
      - name: apt-get install
        run: |
          sudo apt-get update && sudo apt-get install -y expect
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Quartus
        run: docker pull ghcr.io/morriganr/quartus-inst-c5-${{matrix.qver}}:latest

      - name: Install Quartus
        run: |
          docker create -ti --name qsrc ghcr.io/morriganr/quartus-inst-c5-${{matrix.qver}}:latest bash
          echo "# get files" && docker cp qsrc:qinst .
          echo "# rem docker"
          docker rm -f qsrc
          docker rmi -f ghcr.io/morriganr/quartus-inst-c5-${{matrix.qver}}
          echo "# start install"
          cd ./qinst
          Q_INST_DIR=/home/runner/work/intelFPGA_lite
          Q_INST_FILE=$( pwd )/$( ls QuartusLiteSetup-*-linux.run )
          chmod +x $Q_INST_FILE
          ../.docker/play-setup.sh $Q_INST_FILE $Q_INST_DIR
          echo "# rem files"
          cd ../
          rm -rf ./qinst
      - name: Build ${{matrix.example}}
        run: |
          export Q_INST_DIR=/home/runner/work/intelFPGA_lite
          export QUARTUS_ROOTDIR=${Q_INST_DIR}/quartus
          export QUARTUS_ROOTDIR_OVERRIDE=${Q_INST_DIR}/quartus
          export SOPC_KIT_NIOS2=${Q_INST_DIR}/nios2eds
          export PATH=${Q_INST_DIR}/quartus/sopc_builder/bin/:$PATH
          export PATH=${Q_INST_DIR}/quartus/bin/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/bin/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/sdk2/bin/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/bin/gnu/H-x86_64-pc-linux-gnu/bin/:$PATH
          export PATH=${Q_INST_DIR}/quartus/linux64/gnu/:$PATH
          echo "# quartus_sh --version" && quartus_sh --version
          cd /home/runner/work/terasic-de10-nano-kit/terasic-de10-nano-kit/azure-de10nano-document/sensor-aggregation-reference-design-for-azure/hw/${{matrix.example}}/
          echo "# pwd" && pwd
          chmod +x ./build_all_flow.sh
          echo "# ./build_all_flow.sh"
          ./build_all_flow.sh || :
      - name: Prepare artifact ${{matrix.example}}
        id: push_artifact
        run: tar -cvzf ${{matrix.example}}_${{matrix.qver}}.tgz ./sensor-aggregation-reference-design-for-azure/hw/${{matrix.example}}/output_files/

      - name: Push artifact ${{matrix.example}}
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{matrix.example}}_${{matrix.qver}}.tgz
          path: ./${{matrix.example}}_${{matrix.qver}}.tgz
          retention-days: 2
