name: Build Tutorials Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  play-tutorials-job:
    name: Play Tutorials
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get IDE
        run: docker pull ghcr.io/morriganr/q20instc5:latest

      - name: Install IDE
        run: |
          docker create -ti --name qsrc ghcr.io/morriganr/q20instc5:latest bash
          echo "# get files" && docker cp qsrc:qinst .
          echo "# rem docker"
          docker rm -f qsrc
          docker rmi -f ghcr.io/morriganr/q20instc5
          echo "# start install"
          cd ./qinst
          chmod +x *.run
          export Q_INST_DIR=/home/runner/work/terasic-de10-nano-kit/intelFPGA_lite/20.1
          ./QuartusLiteSetup-20.1.1.720-linux.run --mode unattended --installdir ${Q_INST_DIR} --accept_eula 1
          echo "# rem files"
          cd ../
          rm -rf ./qinst

      - name: Compile MyFirstHPSSystem blink
        run: |
          export Q_INST_DIR=/home/runner/work/terasic-de10-nano-kit/intelFPGA_lite/20.1
          export QUARTUS_ROOTDIR=${Q_INST_DIR}/quartus
          export QUARTUS_ROOTDIR_OVERRIDE=${Q_INST_DIR}/quartus
          export SOPC_KIT_NIOS2=${Q_INST_DIR}/nios2eds
          export PATH=${Q_INST_DIR}/quartus/sopc_builder/bin/:$PATH
          export PATH=${Q_INST_DIR}/quartus/bin/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/bin/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/sdk2/bin/:$PATH
          export PATH=${Q_INST_DIR}/nios2eds/bin/gnu/H-x86_64-pc-linux-gnu/bin/:$PATH
          export PATH=${Q_INST_DIR}/quartus/linux64/gnu/:$PATH
          echo "# quartus_sh --version" && quartus_sh --version
          cd /home/runner/work/terasic-de10-nano-kit/terasic-de10-nano-kit/tutorials/MyFirstHPSSystem/
          echo "# pwd" && pwd
          echo "# ./build_example.sh"
          ./build_example.sh || :

      - name: Prepare artifact MyFirstHPSSystem blink
        id: push_artifact
        run: tar -cvzf MyFirstHPSSystem.tgz ./tutorials/MyFirstHPSSystem/blink

      - name: Push artifact MyFirstHPSSystem blink
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MyFirstHPSSystem.tgz
          path: ./MyFirstHPSSystem.tgz
          retention-days: 2
